// Generated by CoffeeScript 1.9.2
var request;

request = require('superagent');

L.GeoTileLayer = L.GridLayer.extend({
  options: {
    maxZoom: 18
  },
  initialize: function(url, options) {
    this._url = url;
    this._tileCache = {};
    return options = L.setOptions(this, options);
  },
  createTile: function(coords, done) {
    var geo, layer, params, requestparams, tile;
    layer = this;
    tile = document.createElement('span');
    params = {
      x: coords.x,
      y: coords.y,
      z: this._tileZoom
    };
    requestparams = {
      x: params.x,
      y: params.y,
      z: params.z
    };
    while (requestparams.z > this.options.zoom) {
      requestparams.x = Math.floor(requestparams.x / 2);
      requestparams.y = Math.floor(requestparams.y / 2);
      requestparams.z -= 1;
    }
    params.url = L.Util.template(this._url, requestparams);
    params.size = this.getTileSize();
    if (this._tileCache[params.url] != null) {
      geo = this._tileCache[params.url];
      layer.options.render(tile, params, geo);
      setTimeout(function() {
        return done(null, tile);
      }, 1);
    } else {
      request.get(params.url).set('Accept', 'application/json').end(function(err, res) {
        if (err != null) {
          return done(err, tile);
        }
        layer._tileCache[params.url] = res.body;
        layer.options.render(tile, params, res.body);
        return done(null, tile);
      });
    }
    return tile;
  }
});

module.exports = function(url, options) {
  return new L.GeoTileLayer(url, options);
};
